Fix the nyc_data_contagg.sql filename in continuous-aggs-tutorial
Fix the nyc_data_contagg.sql filename in continuous-aggs-tutorial

Moreover, in this file under nyc_data.tar.gz (hosted on https://timescaledata.blob.core.windows.net/datasets/nyc_data.tar.gz), these should be added on the top:

```
DROP EXTENSION IF EXISTS timescaledb;
CREATE EXTENSION IF NOT EXISTS timescaledb;
DROP TABLE IF EXISTS "rides";
```

If these are not in the file, it throws the following error:
```
ERROR:  function create_hypertable(unknown, unknown) does not exist
LINE 1: SELECT create_hypertable('rides', 'pickup_datetime');
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```